services:
  database:
    container_name: database
    image: mysql:8.3.0
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - path: ./.env
    expose:
      - 3306
    networks:
      - careerspeak
    volumes:
      - db_data:/var/lib/mysql

networks:
  careerspeak:
    external: true

volumes:
  db_data: {}
