services:
  database:
    container_name: database
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: o#zlF#1fjMFmb038
    expose:
      - 3306
    networks:
      - careerspeak
    volumes:
      - db_data:/var/lib/mysql

networks:
  careerspeak:
    external: true

volumes:
  db_data: {}
